Repository mlemgroup/mlem, pull requests merged in 2023-07, with the labels that each got.

#1 Fix the fat nav bar
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift
Labels: bug

#2 Inbox Interactions
  Mlem.xcodeproj/project.pbxproj
  Mlem/API/APIClient.swift
  Mlem/API/Models/Comments/APICommentReplyView.swift
  Mlem/API/Requests/Messages/CreatePrivateMessageRequest.swift
  Mlem/API/Requests/Messages/MarkPrivateMessageAsReadRequest.swift
  Mlem/API/Requests/Person/MarkCommentReplyAsReadRequest.swift
  Mlem/API/Requests/Person/MarkPersonMentionAsReadRequest.swift
  Mlem/App Constants.swift
  Mlem/Enums/InboxTabs.swift
  Mlem/Extensions/Swipey Actions.swift
  Mlem/Feed/FeedTracker.swift
  Mlem/Logic/Participating/MarkCommentReplyAsRead.swift
  Mlem/Logic/Participating/MarkPersonMentionAsRead.swift
  Mlem/Logic/Participating/MarkPrivateMessageAsRead.swift
  Mlem/Logic/Participating/Post Comment.swift
  Mlem/Logic/Participating/Rate Post or Comment.swift
  Mlem/Logic/Participating/SendPrivateMessage.swift
  Mlem/Views/Shared/Composer/MessageComposerView.swift
  Mlem/Views/Tabs/Inbox/Feed/All Items Feed View.swift
  Mlem/Views/Tabs/Inbox/Feed/InteractionSwipeAndMenuHelpers.swift
  Mlem/Views/Tabs/Inbox/Feed/Item Types/Inbox Mention View.swift
  Mlem/Views/Tabs/Inbox/Feed/Item Types/Inbox Message View.swift
  Mlem/Views/Tabs/Inbox/Feed/Item Types/Inbox Reply View.swift
  Mlem/Views/Tabs/Inbox/Feed/Mentions Feed View.swift
  Mlem/Views/Tabs/Inbox/Feed/Messages Feed View.swift
  Mlem/Views/Tabs/Inbox/Feed/Replies Feed View.swift
  Mlem/Views/Tabs/Inbox/Inbox View Logic.swift
  Mlem/Views/Tabs/Inbox/Inbox View.swift
  Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item Logic.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Expanded Post.swift
Labels: enhancement

#12 Fixed an issue with alignment on the post composer
  Mlem/Views/Shared/Composer/PostComposerView.swift
Labels: bug, ui

#197 Fixed some issues with VO on the accounts page
  Mlem/Views/Tabs/Posts/Components/Post/Components/Instance and Community List/Accounts Page.swift
Labels: bug, accessibility

#206 Handle Instance Offline
  Mlem/API/APIClient.swift
Labels: bug

#278 Re-auth Screen Design Updates
  Mlem/Views/Shared/Composer/PostComposerView.swift
  Mlem/Views/Shared/Links/Community Link View.swift
  Mlem/Views/Shared/TokenRefreshView.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Components/NSFW Tag.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Instance and Community List/Add Account View.swift
Labels: ui, accessibility

#322 Fixed Sort order of Communities to include instance
  Mlem/API/Models/Community/APICommunity.swift
  Mlem/Enums/FeedType.swift
  Mlem/Logic/Get Favorited Communities.swift
  Mlem/Models/Favorite Community.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Community List View.swift
Labels: bug

#323 Missing slash in clays
  Mlem/Assets.xcassets/Icons/Mlem Dark By Clays.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/Mlem Dark By Clays.appiconset/MlemDark-ios.png
Labels: bug

#330 Redesigned Login Screen
  Mlem/Views/Shared/TokenRefreshView.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Community List View.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Instance and Community List/Accounts Page.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Instance and Community List/Add Account View.swift
Labels: ui
