Repository mlemgroup/mlem, pull requests merged in 2024-02, with the labels that each got.

#873 Search Instances
  Mlem.xcodeproj/project.pbxproj
  Mlem/API/APIClient/APIClient.swift
  Mlem/Enums/Content Type.swift
  Mlem/Enums/SearchTab.swift
  Mlem/Models/Content/Instance/InstanceModel+ContentModel.swift
  Mlem/Models/Content/Instance/InstanceModel.swift
  Mlem/Models/Content/Instance/InstanceStub.swift
  Mlem/Models/Trackers/ContentTracker.swift
  Mlem/Models/Trackers/RecentSearchesTracker.swift
  Mlem/Navigation/Routes/AppRoutes.swift
  Mlem/Views/Shared/BadgeView.swift
  Mlem/Views/Shared/Instance/InstanceDetailsView.swift
  Mlem/Views/Shared/Instance/InstanceView.swift
  Mlem/Views/Tabs/Search/RecentSearchesView.swift
  Mlem/Views/Tabs/Search/Results/InstanceResultView.swift
  Mlem/Views/Tabs/Search/SearchModel.swift
  Mlem/Views/Tabs/Search/SearchResultListView.swift
  Mlem/Views/Tabs/Search/SearchResultsView.swift
  Mlem/Views/Tabs/Search/SearchView.swift
Labels: enhancement

#862 Face ID Lock
  Mlem.xcodeproj/project.pbxproj
  Mlem/API/Models/Site/APILocalSite.swift
  Mlem/ContentView.swift
  Mlem/Enums/Settings/AppLock.swift
  Mlem/Extensions/UIDevice/UIDevice+DynamicIsland.swift
  Mlem/Icons.swift
  Mlem/Info.plist
  Mlem/Logic/BiometricUnlock.swift
  Mlem/MlemApp.swift
  Mlem/Models/Content/Instance/InstanceModel+ContentModel.swift
  Mlem/Models/Content/Instance/InstanceModel.swift
  Mlem/Models/Saved Account.swift
  Mlem/Models/Trackers/ContentTracker.swift
  Mlem/Views/Shared/AppLockView.swift
  Mlem/Views/Shared/Instance/InstanceDetailsView.swift
  Mlem/Views/Shared/Instance/InstanceView.swift
  Mlem/Views/Tabs/Search/Results/InstanceResultView.swift
  Mlem/Views/Tabs/Search/SearchModel.swift
  Mlem/Views/Tabs/Search/SearchResultsView.swift
  Mlem/Views/Tabs/Settings/Components/Settings Item.swift
  Mlem/Views/Tabs/Settings/Components/Views/Account/AccountGeneralSettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Account/AccountSettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Account/AdvancedAccountSettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Account/LocalAccountSettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/AccountList/AccountSwitcherSettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/AccountList/QuickSwitcherSettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Appearance/AppearanceSettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/General/GeneralSettingsView.swift
Labels: enhancement

#901 Link Resolution Fix
  Mlem/Extensions/View Modifiers/View+HandleLemmyLinks.swift
Labels: bug

#899 Bubble picker scroll-on-tap
  Mlem/Views/Tabs/Search/BubblePicker.swift
Labels: enhancement

#898 Fix "no items" message in Saved Feed appearing momentarily before content loads
  Mlem/Models/Trackers/Generics/StandardTracker.swift
  Mlem/Views/Tabs/Feeds/Components/UserContentFeedView.swift
Labels: bug

#897 Fix "Show n replies" button tap area
  Mlem/Views/Shared/Comments/Comment Item.swift
Labels: bug

#894 Fix blocking communities from posts
  Mlem/Models/Content/Community/CommunityModel.swift
  Mlem/Models/Content/Post/PostModel.swift
Labels: bug

#908 Updated search bar prompt
  Mlem/Views/Tabs/Search/RecentSearchesView.swift
  Mlem/Views/Tabs/Search/SearchView.swift
Labels: ui

#916 Fix changing avatar externally failing to update `SavedAccount`
  Mlem/Models/Trackers/SiteInformationTracker.swift
Labels: bug

#915 Fix Community/User instance caption app startup inconsistency
  Mlem/Views/Shared/Posts/Expanded Post.swift
Labels: bug

#921 Update Saved feed caption
  Mlem/Views/Tabs/Feeds/Components/FeedHeaderView.swift
Labels: ui

#878 Ban Users
  Mlem.xcodeproj/project.pbxproj
  Mlem/API/APIClient/APIClient.swift
  Mlem/API/Requests/Person/BanPerson.swift
  Mlem/ContentView.swift
  Mlem/Extensions/View Modifiers/View+DestructiveConfirmation.swift
  Mlem/Icons.swift
  Mlem/Models/Composers/Administration/BanUserEditorModel.swift
  Mlem/Models/Content/Community/CommunityModel+MenuFunctions.swift
  Mlem/Models/Content/Inbox/MentionModel.swift
  Mlem/Models/Content/Inbox/MessageModel.swift
  Mlem/Models/Content/Inbox/ReplyModel.swift
  Mlem/Models/Content/Post/PostModel+MenuFunctions.swift
  Mlem/Models/Content/User/UserModel+MenuFunctions.swift
  Mlem/Models/Content/User/UserModel.swift
  Mlem/Models/Menu Function.swift
  Mlem/Models/Trackers/Editor Tracker.swift
  Mlem/Models/Trackers/SiteInformationTracker.swift
  Mlem/Temp Image Viewer/ZoomableImageView.swift
  Mlem/Views/Shared/Comments/Comment Item Logic.swift
  Mlem/Views/Shared/Components/Components/Menu Button.swift
  Mlem/Views/Shared/Composer/BanUserView.swift
  Mlem/Views/Shared/Posts/ExpandedPostLogic.swift
  Mlem/Views/Tabs/Feeds/Components/PostFeedView+MenuFunctions.swift
  Mlem/Views/Tabs/Feeds/Components/UserContentFeedView+Logic.swift
  Mlem/Views/Tabs/Feeds/Feed Types/AggregateFeedView+Logic.swift
  Mlem/Views/Tabs/Inbox/InboxView+Logic.swift
  Mlem/Views/Tabs/Profile/UserView.swift
  Mlem/Views/Tabs/Search/Results/UserResultView.swift
Labels: enhancement

#884 Instance Uptime
  Mlem.xcodeproj/project.pbxproj
  Mlem/Extensions/View Modifiers/View+HandleLemmyLinks.swift
  Mlem/Icons.swift
  Mlem/Models/Content/Community/CommunityModel+MenuFunctions.swift
  Mlem/Models/Content/Instance/InstanceModel+Uptime.swift
  Mlem/Models/Content/Instance/InstanceModel.swift
  Mlem/Models/Content/User/UserModel+MenuFunctions.swift
  Mlem/Navigation/Routes/AppRoutes.swift
  Mlem/Views/Shared/Instance/InstanceUptimeView.swift
  Mlem/Views/Shared/Instance/InstanceView.swift
  Mlem/Views/Shared/Instance/UptimeData.swift
  Mlem/Views/Tabs/Search/Results/InstanceResultView.swift
Labels: enhancement, ui

#954 Disable collapse animations when "Reduce Motion" is on
  Mlem.xcodeproj/project.pbxproj
  Mlem/Animations/Animations.swift
  Mlem/Views/Shared/Posts/Expanded Post.swift
  Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift
Labels: accessibility
