Repository mlemgroup/mlem, pull requests merged in 2024-01, with the labels that each got.

#852 Fix toggling "hide read" not immediately updating
  Mlem/Views/Tabs/Feeds/PostFeedView.swift
Labels: bug

#849 Fix community "Favorite" action being shown when it shouldn't
  Mlem/Models/Content/Community/CommunityModel+MenuFunctions.swift
  Mlem/Models/Content/Community/CommunityModel+SwipeActions.swift
Labels: bug

#848 Fix "Show score in info" setting default value inconsistency
  Mlem/Views/Shared/Comments/Comment Item.swift
  Mlem/Views/Shared/Posts/Expanded Post.swift
  Mlem/Views/Shared/Posts/Feed Post.swift
  Mlem/Views/Tabs/Settings/Components/Views/Appearance/Post/PostSettingsView.swift
Labels: bug

#847 Fix Sort Mode Labelling Inconsistency
  Mlem/Enums/Settings/PostSortType.swift
  Mlem/Views/Shared/Comments/Comment Item Logic.swift
Labels: bug

#859 "Open Links in Default Browser" Setting
  Mlem/Logic/URLHandler.swift
  Mlem/Views/Tabs/Settings/Components/Views/General/GeneralSettingsView.swift
Labels: enhancement

#857 Community Favorite Fix
  Mlem/Models/Content/Community/CommunityModel.swift
Labels: bug, ui

#851 Matrix ID Settings Bug Fixes & UI Tweaks
  Mlem/Views/Tabs/Settings/Components/Views/Account/MatrixLinkView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Account/ProfileSettingsView.swift
Labels: bug, ui

#858 New Comments Indicator
  Mlem/Icons.swift
  Mlem/Models/Content/Post Model.swift
  Mlem/Views/Shared/Comments/Comment Item.swift
  Mlem/Views/Shared/Components/Components/InfoStackView.swift
  Mlem/Views/Shared/Components/InteractionBarView.swift
  Mlem/Views/Shared/Posts/Expanded Post.swift
  Mlem/Views/Shared/Posts/ExpandedPostLogic.swift
  Mlem/Views/Shared/Posts/Feed Post.swift
  Mlem/Views/Shared/Posts/Post Sizes/Compact Post.swift
Labels: enhancement, ui

#850 Fix `flowDidChange` being called extraneously
  Mlem/Views/Tabs/Profile/Profile View.swift
  Mlem/Window.swift
Labels: bug

#876 Setting to Disable Tap-to-Collapse
  Mlem/Icons.swift
  Mlem/Views/Shared/Comments/Comment Item.swift
  Mlem/Views/Tabs/Settings/Components/Views/General/GeneralSettingsView.swift
Labels: enhancement

#853 Fix NSFW Community Search Result title bug
  Mlem/Views/Shared/Cached Image.swift
  Mlem/Views/Shared/Components/Thumbnail Image View.swift
  Mlem/Views/Shared/Links/AvatarView.swift
  Mlem/Views/Tabs/Search/Results/CommunityResultView.swift
Labels: bug, ui

#856 Instance Page
  Mlem.xcodeproj/project.pbxproj
  Mlem/API/APIClient/APIClient.swift
  Mlem/API/Requests/Person/GetPersonDetails.swift
  Mlem/Enums/AvatarType.swift
  Mlem/Extensions/View Modifiers/View+HandleLemmyLinks.swift
  Mlem/Models/Content/Community/CommunityModel+MenuFunctions.swift
  Mlem/Models/Content/Community/CommunityModel.swift
  Mlem/Models/Content/Instance/InstanceModel+MenuFunctions.swift
  Mlem/Models/Content/Instance/InstanceModel.swift
  Mlem/Models/Content/Post Model.swift
  Mlem/Models/Content/User/UserModel+MenuFunctions.swift
  Mlem/Models/Content/User/UserModel.swift
  Mlem/Models/Menu Function.swift
  Mlem/Models/Trackers/SiteInformationTracker.swift
  Mlem/Navigation/Routes/AppRoutes.swift
  Mlem/Repositories/PersonRepository.swift
  Mlem/Views/Shared/Avatars/DefaultAvatarView.swift
  Mlem/Views/Shared/Components/Components/Menu Button.swift
  Mlem/Views/Shared/Error View.swift
  Mlem/Views/Shared/Instance/InstanceView.swift
  Mlem/Views/Shared/Links/AvatarView.swift
  Mlem/Views/Tabs/Profile/AvatarBannerView.swift
  Mlem/Views/Tabs/Profile/UserFeedView.swift
  Mlem/Views/Tabs/Profile/UserView+Logic.swift
  Mlem/Views/Tabs/Profile/UserView.swift
  Mlem/Views/Tabs/Search/RecentSearchesView.swift
  Mlem/Views/Tabs/Search/Results/CommunityResultView.swift
  Mlem/Views/Tabs/Search/Results/UserResultView.swift
  Mlem/Views/Tabs/Search/SearchResultListView.swift
Labels: enhancement, ui

#854 User Settings UI Consistency with User Profile
  Mlem/Views/Tabs/Profile/UserView.swift
  Mlem/Views/Tabs/Settings/Components/SettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Account/AccountSettingsView.swift
Labels: ui

#866 Edit Profile from "Profile" tab
  Mlem/API/Models/Person/APIPerson.swift
  Mlem/ContentView.swift
  Mlem/Models/Content/Instance/InstanceModel.swift
  Mlem/Models/Content/User/UserModel.swift
  Mlem/Views/Tabs/Profile/Profile View.swift
  Mlem/Views/Tabs/Profile/UserFeedView.swift
  Mlem/Views/Tabs/Profile/UserView.swift
  Mlem/Views/Tabs/Search/Results/UserResultView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Account/MatrixLinkView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Account/ProfileSettingsView.swift
Labels: enhancement

#860 Image Links & Badges
  Mlem.xcodeproj/project.pbxproj
  Mlem/Assets.xcassets/Symbols/Contents.json
  Mlem/Assets.xcassets/Symbols/discord.logo.symbolset/Contents.json
  Mlem/Assets.xcassets/Symbols/discord.logo.symbolset/discord-symbol.svg
  Mlem/Assets.xcassets/Symbols/github.logo.symbolset/Contents.json
  Mlem/Assets.xcassets/Symbols/github.logo.symbolset/logo.github.svg
  Mlem/Assets.xcassets/Symbols/lemmy.logo.symbolset/Contents.json
  Mlem/Assets.xcassets/Symbols/lemmy.logo.symbolset/lemmy-symbol.svg
  Mlem/Assets.xcassets/Symbols/mastodon.logo.symbolset/Contents.json
  Mlem/Assets.xcassets/Symbols/mastodon.logo.symbolset/mastodon-symbol.svg
  Mlem/Assets.xcassets/Symbols/matrix.logo.symbolset/Contents.json
  Mlem/Assets.xcassets/Symbols/matrix.logo.symbolset/matrix-favicon-symbol.svg
  Mlem/Assets.xcassets/mlem.symbolset/mlem.1.svg
  Mlem/Extensions/Color/Color+Hex.swift
  Mlem/Views/Shared/BadgeView.swift
  Mlem/Views/Shared/Markdown View.swift
  Mlem/Views/Shared/MarkdownTheme.swift
  Mlem/Views/Tabs/Settings/Components/Views/About/AboutView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Account/MatrixLinkView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Account/ProfileSettingsView.swift
Labels: enhancement, ui

#863 Fix Account list sorting issue
  Mlem/Views/Tabs/Settings/Components/AccountListView+Logic.swift
Labels: bug

#870 Custom Account Sort Order
  Mlem/Enums/Settings/AccountSortMode.swift
  Mlem/Views/Tabs/Settings/Components/AccountListView+Logic.swift
  Mlem/Views/Tabs/Settings/Components/AccountListView.swift
Labels: enhancement

#877 iOS 16 symbol fix
  Mlem/Icons.swift
Labels: bug

#867 Slur Filter Warning
  Mlem/API/Models/Site/APILocalSite.swift
  Mlem/Models/Composers/Response Composers/EditorModelProtocol.swift
  Mlem/Models/Composers/Response Composers/Editors/CommentEditor.swift
  Mlem/Models/Composers/Response Composers/Replies/ReplyToComment.swift
  Mlem/Models/Composers/Response Composers/Replies/ReplyToCommentReply.swift
  Mlem/Models/Composers/Response Composers/Replies/ReplyToMention.swift
  Mlem/Models/Composers/Response Composers/Replies/ReplyToMessage.swift
  Mlem/Models/Composers/Response Composers/Replies/ReplyToPost.swift
  Mlem/Models/Composers/Response Composers/Reports/ReportComment.swift
  Mlem/Models/Composers/Response Composers/Reports/ReportCommentReply.swift
  Mlem/Models/Composers/Response Composers/Reports/ReportMention.swift
  Mlem/Models/Composers/Response Composers/Reports/ReportMessage.swift
  Mlem/Models/Composers/Response Composers/Reports/ReportPost.swift
  Mlem/Models/Content/Instance/InstanceModel.swift
  Mlem/Models/Trackers/SiteInformationTracker.swift
  Mlem/Views/Shared/Components/Image Upload/LinkAttachmentModel.swift
  Mlem/Views/Shared/Composer/PostComposerView+Logic.swift
  Mlem/Views/Shared/Composer/PostComposerView.swift
  Mlem/Views/Shared/Composer/ResponseEditorView.swift
Labels: enhancement

#840 New App Icon Selector
  Mlem.xcodeproj/project.pbxproj
  Mlem/Assets.xcassets/Icons/icon.aaron.beehaw.appiconset/Beehaw Mlem Atomic 2-06.png
  Mlem/Assets.xcassets/Icons/icon.aaron.beehaw.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.clays.beehaw.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.clays.beehaw.appiconset/Mlemhaw-ios.png
  Mlem/Assets.xcassets/Icons/icon.clays.conductor.appiconset/ConductorLem.png
  Mlem/Assets.xcassets/Icons/icon.clays.conductor.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.clays.cream.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.clays.cream.appiconset/MlemCream-ios.png
  Mlem/Assets.xcassets/Icons/icon.clays.dark.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.clays.dark.appiconset/MlemDark-ios.png
  Mlem/Assets.xcassets/Icons/icon.clays.default.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.clays.default.appiconset/mlemmy-brighter.png
  Mlem/Assets.xcassets/Icons/icon.clays.dev.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.clays.dev.appiconset/MlemDev-ios.png
  Mlem/Assets.xcassets/Icons/icon.clays.lime.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.clays.lime.appiconset/MlemLime-ios.png
  Mlem/Assets.xcassets/Icons/icon.clays.mono.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.clays.mono.appiconset/MlemMono-ios.png
  Mlem/Assets.xcassets/Icons/icon.clays.pride.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.clays.pride.appiconset/MlemPride-ios.png
  Mlem/Assets.xcassets/Icons/icon.clays.pride2.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.clays.pride2.appiconset/MlemInclusivePride-ios.png
  Mlem/Assets.xcassets/Icons/icon.clays.pumpkin.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.clays.pumpkin.appiconset/MlemkinSpice-ios.png
  Mlem/Assets.xcassets/Icons/icon.clays.red.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.clays.red.appiconset/Mlemmit-ios.png
  Mlem/Assets.xcassets/Icons/icon.clays.trans.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.clays.trans.appiconset/MlemTransPride-ios.png
  Mlem/Assets.xcassets/Icons/icon.clays.wave.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.clays.wave.appiconset/MlemWave-ios.png
  Mlem/Assets.xcassets/Icons/icon.eric.lemmy.appiconset/Classic Lemmy.png
  Mlem/Assets.xcassets/Icons/icon.eric.lemmy.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.sjmarf.alien.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.sjmarf.alien.appiconset/logo.png
  Mlem/Assets.xcassets/Icons/icon.sjmarf.default.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.sjmarf.default.appiconset/logo.png
  Mlem/Assets.xcassets/Icons/icon.sjmarf.green.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.sjmarf.green.appiconset/green.png
  Mlem/Assets.xcassets/Icons/icon.sjmarf.orange.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.sjmarf.orange.appiconset/orange.png
  Mlem/Assets.xcassets/Icons/icon.sjmarf.pink.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.sjmarf.pink.appiconset/pink.png
  Mlem/Assets.xcassets/Icons/icon.sjmarf.silver.appiconset/Contents.json
  Mlem/Assets.xcassets/Icons/icon.sjmarf.silver.appiconset/logo.png
  Mlem/Logic/Easter/Easter Rewards.swift
  Mlem/Models/Settings/AlternativeIcon.swift
  Mlem/Views/Shared/CollapsibleSection.swift
  Mlem/Views/Tabs/Settings/Components/Views/Appearance/Icons/AlternativeIconCell.swift
  Mlem/Views/Tabs/Settings/Components/Views/Appearance/Icons/AlternativeIconLabel.swift
  Mlem/Views/Tabs/Settings/Components/Views/Appearance/Icons/IconSettingsView.swift
Labels: ui

#882 Link context actions
  Mlem/Views/Shared/Components/EasyTapLinkView.swift
  Mlem/Views/Shared/Website Icon Complex.swift
Labels: ui

#881 Consolidate Post Menu Functions into `PostModel`
  Mlem.xcodeproj/project.pbxproj
  Mlem/Models/Content/Post/PostModel+MenuFunctions.swift
  Mlem/Models/Content/Post/PostModel.swift
  Mlem/Models/Content/User/UserModel.swift
  Mlem/Views/Shared/Posts/Expanded Post.swift
  Mlem/Views/Shared/Posts/ExpandedPostLogic.swift
  Mlem/Views/Shared/Posts/Feed Post.swift
Labels: ui, refactor

#841 Automatic collapse child comments
  Mlem.xcodeproj/project.pbxproj
  Mlem/API/Internal/HierarchicalComment.swift
  Mlem/API/Models/Site/APILocalSite.swift
  Mlem/ContentView.swift
  Mlem/Icons.swift
  Mlem/Models/Content/Community/CommunityModel+MenuFunctions.swift
  Mlem/Models/Content/Instance/InstanceModel.swift
  Mlem/Models/Content/Post/PostModel+MenuFunctions.swift
  Mlem/Models/Content/User/UserModel+MenuFunctions.swift
  Mlem/Models/Content/User/UserModel.swift
  Mlem/Models/Trackers/SiteInformationTracker.swift
  Mlem/Repositories/PersonRepository.swift
  Mlem/Views/Shared/BadgeView.swift
  Mlem/Views/Shared/CollapsibleSection.swift
  Mlem/Views/Shared/Comments/Comment Item Logic.swift
  Mlem/Views/Shared/Comments/Comment Item.swift
  Mlem/Views/Shared/Comments/Components/CollapsedCommentReplies.swift
  Mlem/Views/Shared/Components/Image Upload/LinkAttachmentModel.swift
  Mlem/Views/Shared/Composer/PostComposerView.swift
  Mlem/Views/Shared/Error View.swift
  Mlem/Views/Shared/Instance/InstanceView.swift
  Mlem/Views/Shared/Links/AvatarView.swift
  Mlem/Views/Shared/Markdown View.swift
  Mlem/Views/Shared/MarkdownTheme.swift
  Mlem/Views/Shared/Posts/Expanded Post.swift
  Mlem/Views/Tabs/Feeds/Feed Types/AggregateFeedView.swift
  Mlem/Views/Tabs/Profile/AvatarBannerView.swift
  Mlem/Views/Tabs/Profile/Profile View.swift
  Mlem/Views/Tabs/Profile/UserFeedView.swift
  Mlem/Views/Tabs/Profile/UserView.swift
  Mlem/Views/Tabs/Search/RecentSearchesView.swift
  Mlem/Views/Tabs/Search/Results/CommunityResultView.swift
  Mlem/Views/Tabs/Search/Results/UserResultView.swift
  Mlem/Views/Tabs/Search/SearchResultListView.swift
  Mlem/Views/Tabs/Settings/Components/AccountListView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Account/AccountSettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Appearance/Comment/CommentSettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Appearance/Icons/AlternativeIconLabel.swift
Labels: enhancement, ui

#885 Rename Community "Statistics" tab to "Details"
  Mlem.xcodeproj/project.pbxproj
  Mlem/Views/Tabs/Feeds/Components/CommunityDetailsView.swift
  Mlem/Views/Tabs/Feeds/Feed Types/CommunityFeedView.swift
Labels: ui

#872 Rearrange Settings
  Mlem.xcodeproj/project.pbxproj
  Mlem/App State.swift
  Mlem/ContentView.swift
  Mlem/Enums/Settings/ProfileTabLabel.swift
  Mlem/Extensions/View Modifiers/View+HandleLemmyLinks.swift
  Mlem/Icons.swift
  Mlem/Models/Saved Account.swift
  Mlem/Navigation/Destination Values/SettingsValues.swift
  Mlem/Views/Tabs/Settings/Components/Settings Item.swift
  Mlem/Views/Tabs/Settings/Components/Views/Account/AccountGeneralSettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Account/AccountSettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Account/AdvancedAccountSettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Account/LocalAccountSettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/AccountList/AccountSwitcherSettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/AccountList/QuickSwitcherSettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Appearance/AppearanceSettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Appearance/TabBar/TabBarSettingsView.swift
  Mlem/Views/Tabs/Settings/Components/Views/General/GeneralSettingsView.swift
Labels: ui

#869 Instance Statistics
  Mlem.xcodeproj/project.pbxproj
  Mlem/API/Models/Community/APICommunityAggregates.swift
  Mlem/API/Models/Site/APILocalSite.swift
  Mlem/Extensions/Date/Date+Formatter.swift
  Mlem/Extensions/Date/Date+RelativeTime.swift
  Mlem/Extensions/Mocks/APICommunityAggregates+Mock.swift
  Mlem/Icons.swift
  Mlem/Models/Content/Community/CommunityModel.swift
  Mlem/Models/Content/Instance/InstanceModel.swift
  Mlem/Models/UserFlair.swift
  Mlem/Notifications/NotificationDisplayer.swift
  Mlem/Views/Shared/Instance/InstanceDetailsView.swift
  Mlem/Views/Shared/Instance/InstanceView.swift
  Mlem/Views/Tabs/Feeds/Components/CommunityDetailsView.swift
  Mlem/Views/Tabs/Profile/UserView+Logic.swift
  Mlem/Views/Tabs/Profile/UserView.swift
  Mlem/Views/Tabs/Settings/Components/Views/Advanced/AdvancedSettingsView.swift
Labels: enhancement
